### ISSUE TITLE
ClassCastException when trying to list all users

### ISSUE THREAD

**Issue by martin-g** [estatio/estatio#9]
While testing issue #6 I have faced:

````
Caused by: org.apache.isis.applib.FatalException: org.isisaddons.module.command.dom.CommandJdo cannot be cast to org.apache.isis.applib.services.command.Command3
	at org.apache.isis.core.metamodel.facets.DomainEventHelper.postEventForAction(DomainEventHelper.java:105)
	at org.apache.isis.core.metamodel.facets.actions.action.invocation.ActionInvocationFacetForDomainEventAbstract.invoke(ActionInvocationFacetForDomainEventAbstract.java:184)
	at org.apache.isis.core.runtime.transaction.facets.ActionInvocationFacetWrapTransaction$1.execute(ActionInvocationFacetWrapTransaction.java:57)
	at org.apache.isis.core.runtime.transaction.facets.ActionInvocationFacetWrapTransaction$1.execute(ActionInvocationFacetWrapTransaction.java:54)
	at org.apache.isis.core.runtime.system.transaction.IsisTransactionManager.executeWithinTransaction(IsisTransactionManager.java:205)
	at org.apache.isis.core.runtime.transaction.facets.ActionInvocationFacetWrapTransaction.invoke(ActionInvocationFacetWrapTransaction.java:54)
	at org.apache.isis.core.metamodel.specloader.specimpl.ObjectActionImpl.execute(ObjectActionImpl.java:367)
	at org.apache.isis.core.metamodel.specloader.specimpl.ObjectActionImpl.executeWithRuleChecking(ObjectActionImpl.java:358)
	at org.apache.isis.viewer.wicket.model.models.ActionModel.executeAction(ActionModel.java:465)
	at org.apache.isis.viewer.wicket.model.models.ActionModel.load(ActionModel.java:445)
	at org.apache.isis.viewer.wicket.model.models.ActionModel.load(ActionModel.java:78)
	at org.apache.wicket.model.LoadableDetachableModel.getObject(LoadableDetachableModel.java:121)
	at org.apache.isis.viewer.wicket.model.models.ActionModel.executeHandlingApplicationExceptions(ActionModel.java:541)
	at org.apache.isis.viewer.wicket.ui.components.actions.ActionPanel.executeActionOnTargetAndProcessResults(ActionPanel.java:245)
	at org.apache.isis.viewer.wicket.ui.components.actions.ActionPanel.executeActionAndProcessResults(ActionPanel.java:193)
	at org.apache.isis.viewer.wicket.ui.components.actions.ActionPanel.buildGui(ActionPanel.java:104)
	at org.apache.isis.viewer.wicket.ui.components.actions.ActionPanel.<init>(ActionPanel.java:82)
	at org.apache.isis.viewer.wicket.ui.components.actions.ActionPanelFactory.createComponent(ActionPanelFactory.java:49)
	at org.apache.isis.viewer.wicket.viewer.registries.components.ComponentFactoryRegistryDefault.createComponent(ComponentFactoryRegistryDefault.java:128)
	at org.apache.isis.viewer.wicket.ui.components.widgets.linkandlabel.ActionLinkFactoryAbstract$1.onClick(ActionLinkFactoryAbstract.java:77)
	at org.apache.wicket.ajax.markup.html.AjaxLink$1.onEvent(AjaxLink.java:86)
	at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:124)
	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:633)
	... 39 more
Caused by: java.lang.ClassCastException: org.isisaddons.module.command.dom.CommandJdo cannot be cast to org.apache.isis.applib.services.command.Command3
	at org.apache.isis.core.metamodel.facets.DomainEventHelper.postEventForAction(DomainEventHelper.java:81)
````

The exception happens both with jetty-console and in IDEA with WebServer.

Steps to reproduce:
- login with `isis-module-security-admin`
- navigate to "Security" > "All users"

Do I miss some setup step or it is a bug ?

**Comment by danhaywood** [comment]
Rebuild isis-module-command ... the CommandJdo class is defined there and
now implements this new interface.

**Comment by martin-g** [comment]
I didn't have isis-module-command locally until now.
I just `mvn clean install`ed it but Estatio still fails with the same error.
I'll import it in the IDE to link the projects and see.

**Comment by martin-g** [comment]
Now it fails at start with:
````
java.lang.ClassCastException: org.datanucleus.store.rdbms.mapping.java.SerialisedMapping cannot be cast to org.datanucleus.store.rdbms.mapping.java.PersistableMapping
````

**Comment by danhaywood** [comment]
The isis-module-command has entities, so these need to be enhanced prior to
starting the app (Maven goals on the launch config).

**Comment by martin-g** [comment]
Everything seems to be OK now!
Thanks!

But needing to build isis-module-command locally makes me think that maybe Cloudbees repo doesn't serve well for some reason.

**Comment by danhaywood** [comment]
agreed; something must be awry.  Could you chase with Jeroen to get access
and have a poke around?
