### ISSUE TITLE
Demo Fixture Script Not working

### ISSUE THREAD

**Issue by Ndiya999** [estatio/estatio#92]
Good day,

I am trying to setup Estatio locally in order for me to get a look and feel.
However the Demo fixture scripts do not work. I keep on getting NullPointerExceptions or a server error depending on which script I run.

Please assist.

**Comment by sanderginn** [comment]
Hi,

We cannot help you without at least a stack trace. Please post the exceptions you are running into.

**Comment by Ndiya999** [comment]
Sorry about that. Please find stack trace: 
<pre>[java] [Thread-2] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@73355eab{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
     [java] 13:53:59,296 [IsisWicketApplication         ] DebugDiskDataStore registered; access via ~/wicket/internal/debug/diskDataStore[Thread-2] INFO org.eclipse.jetty.server.Server - Started @31601ms
     [java]
     [java] 13:53:59,296 [IsisWicketApplication         ] DebugDiskDataStore: eg, http://localhost:8080/wicket/wicket/internal/debug/diskDataStore
     [java] 13:53:59,296 [IsisWicketApplication         ] storeSettings.inmemoryCacheSize        : 0
     [java] 13:53:59,296 [IsisWicketApplication         ] storeSettings.asynchronousQueueCapacity: 100
     [java] 13:53:59,296 [IsisWicketApplication         ] storeSettings.maxSizePerSession        : 10M
     [java] 13:53:59,296 [IsisWicketApplication         ] storeSettings.fileStoreFolder          : /private/var/folders/c_/470c9f8d4rn2bwr4z87j1p6w0000gn/T/estatio-webapp-1.29.0-SNAPSHOT-jetty-console.war_8080
     [java] 13:53:59,297 [ThreadPoolSupport             ] join'ing 6 tasks: waited 1 milliseconds
     [java] 13:53:59,300 [WebApplication                ] [wicket.estatio] Started Wicket version 7.9.0 in DEVELOPMENT mode
     [java] 13:54:58,408 [ClassCryptFactory             ] using encryption/decryption object org.apache.wicket.util.crypt.SunJceCrypt@3db611c2
     [java] 13:55:17,329 [RequestCycleExtra             ] ********************************
     [java] 13:55:17,330 [RequestCycleExtra             ] Handling the following exception
     [java] org.apache.wicket.WicketRuntimeException: Method onRequest of interface org.apache.wicket.behavior.IBehaviorListener targeted at org.apache.wicket.ajax.markup.html.AjaxLink$1@53d540ff on component [ActionLink [Component id = menuLink]] threw an exception
     [java] 	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:268)
     [java] 	at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:241)
     [java] 	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:248)
     [java] 	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:234)
     [java] 	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
     [java] 	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     [java] 	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
     [java] 	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
     [java] 	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
     [java] 	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
     [java] 	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
     [java] 	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
     [java] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
     [java] 	at org.togglz.servlet.TogglzFilter.doFilter(TogglzFilter.java:100)
     [java] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
     [java] 	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
     [java] 	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
     [java] 	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
     [java] 	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
     [java] 	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
     [java] 	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
     [java] 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
     [java] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
     [java] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
     [java] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
     [java] 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
     [java] 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
     [java] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
     [java] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
     [java] 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
     [java] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
     [java] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
     [java] 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
     [java] 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
     [java] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
     [java] 	at org.eclipse.jetty.server.Server.handle(Server.java:517)
     [java] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
     [java] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
     [java] 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
     [java] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
     [java] 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
     [java] 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
     [java] 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
     [java] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
     [java] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
     [java] 	at java.lang.Thread.run(Thread.java:748)
     [java] Caused by: java.lang.reflect.InvocationTargetException
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258)
     [java] 	... 45 more
     [java] Caused by: java.lang.NullPointerException
     [java] 	at org.estatio.module.base.app.EstatioSecurityModuleFixturesMenu.installFixturesAndReturnFirstRole(EstatioSecurityModuleFixturesMenu.java:95)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at org.apache.isis.core.metamodel.facets.actions.action.invocation.ActionInvocationFacetForDomainEventAbstract.invokeMethodElseFromCache(ActionInvocationFacetForDomainEventAbstract.java:407)
     [java] 	at org.apache.isis.core.metamodel.facets.actions.action.invocation.ActionInvocationFacetForDomainEventAbstract$2.execute(ActionInvocationFacetForDomainEventAbstract.java:261)
     [java] 	at org.apache.isis.core.metamodel.facets.actions.action.invocation.ActionInvocationFacetForDomainEventAbstract$2.execute(ActionInvocationFacetForDomainEventAbstract.java:222)
     [java] 	at org.apache.isis.applib.services.iactn.Interaction.executeInternal(Interaction.java:173)
     [java] 	at org.apache.isis.applib.services.iactn.Interaction.execute(Interaction.java:143)
     [java] 	at org.apache.isis.core.metamodel.facets.actions.action.invocation.ActionInvocationFacetForDomainEventAbstract.doInvoke(ActionInvocationFacetForDomainEventAbstract.java:310)
     [java] 	at org.apache.isis.core.metamodel.facets.actions.action.invocation.ActionInvocationFacetForDomainEventAbstract$1.execute(ActionInvocationFacetForDomainEventAbstract.java:164)
     [java] 	at org.apache.isis.core.runtime.system.transaction.IsisTransactionManager.executeWithinTransaction(IsisTransactionManager.java:142)
     [java] 	at org.apache.isis.core.runtime.system.transaction.IsisTransactionManager.executeWithinTransaction(IsisTransactionManager.java:132)
     [java] 	at org.apache.isis.core.runtime.services.persistsession.PersistenceSessionServiceInternalDefault.executeWithinTransaction(PersistenceSessionServiceInternalDefault.java:192)
     [java] 	at org.apache.isis.core.metamodel.facets.actions.action.invocation.ActionInvocationFacetForDomainEventAbstract.invoke(ActionInvocationFacetForDomainEventAbstract.java:160)
     [java] 	at org.apache.isis.core.metamodel.specloader.specimpl.ObjectActionDefault.executeInternal(ObjectActionDefault.java:400)
     [java] 	at org.apache.isis.core.metamodel.specloader.specimpl.ObjectActionDefault.execute(ObjectActionDefault.java:389)
     [java] 	at org.apache.isis.core.metamodel.specloader.specimpl.ObjectActionDefault.executeWithRuleChecking(ObjectActionDefault.java:370)
     [java] 	at org.apache.isis.viewer.wicket.model.models.ActionModel.executeAction(ActionModel.java:460)
     [java] 	at org.apache.isis.viewer.wicket.model.models.ActionModel.load(ActionModel.java:439)
     [java] 	at org.apache.isis.viewer.wicket.model.models.ActionModel.load(ActionModel.java:76)
     [java] 	at org.apache.wicket.model.LoadableDetachableModel.getObject(LoadableDetachableModel.java:135)
     [java] 	at org.apache.isis.viewer.wicket.model.models.ActionModel.execute(ActionModel.java:569)
     [java] 	at org.apache.isis.viewer.wicket.ui.components.actions.ActionFormExecutorStrategy.obtainResultAdapter(ActionFormExecutorStrategy.java:71)
     [java] 	at org.apache.isis.viewer.wicket.ui.panels.FormExecutorDefault.obtainResultAdapter(FormExecutorDefault.java:514)
     [java] 	at org.apache.isis.viewer.wicket.ui.panels.FormExecutorDefault.executeAndProcessResults(FormExecutorDefault.java:147)
     [java] 	at org.apache.isis.viewer.wicket.ui.components.widgets.linkandlabel.ActionLinkFactoryAbstract.onClick(ActionLinkFactoryAbstract.java:214)
     [java] 	at org.apache.isis.viewer.wicket.ui.components.widgets.linkandlabel.ActionLinkFactoryAbstract.access$100(ActionLinkFactoryAbstract.java:71)
     [java] 	at org.apache.isis.viewer.wicket.ui.components.widgets.linkandlabel.ActionLinkFactoryAbstract$1.performOnClick(ActionLinkFactoryAbstract.java:147)
     [java] 	at org.apache.isis.viewer.wicket.ui.components.widgets.linkandlabel.ActionLinkFactoryAbstract$1.doOnClick(ActionLinkFactoryAbstract.java:142)
     [java] 	at org.apache.isis.viewer.wicket.ui.components.widgets.linkandlabel.ActionLink.onClick(ActionLink.java:94)
     [java] 	at org.apache.wicket.ajax.markup.html.AjaxLink$1.onEvent(AjaxLink.java:85)
     [java] 	at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:155)
     [java] 	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:601)
     [java] 	... 50 more
     [java] 13:55:17,331 [RequestCycleExtra             ] ********************************
     [java] 13:55:17,337 [IsisTransaction               ] abort transaction IsisTransaction@5da574f9[state=MUST_ABORT,commands=0]</pre>

**Comment by Ndiya999** [comment]
Steps to reproduce: 
1) login as admin
2) Navigate to the "Prototyping" tab
3) Click on "Install fixtures and return first role"

**Comment by Ndiya999** [comment]
Any feedback on this? @sanderginn
